/// <reference types="cypress" />
context('Viewport', () => {
    beforeEach(() => {
      cy.visit('http://localhost:8080')
    })
    it('cy.viewport() - set the viewport size and dimension', () => {
        cy.wait(1000)
        cy.viewport('macbook-13')
        cy.wait(1000)
        cy.viewport('macbook-11')
        cy.wait(1000)
        cy.viewport('ipad-2')
        cy.wait(1000)
        cy.viewport('ipad-mini')
        cy.wait(1000)
        cy.viewport('iphone-6+')
        cy.wait(1000)
        cy.viewport('iphone-6')
        cy.wait(1000)
        cy.viewport('iphone-7')
        cy.wait(1000)
        cy.viewport('iphone-8')
        cy.wait(1000)
        cy.viewport('iphone-x')
        cy.wait(1000)
        cy.wait(1000)
        cy.viewport('ipad-2', 'portrait')
        cy.wait(1000)
        cy.viewport('macbook-15')
        cy.viewport(1920, 1080)
        cy.viewport('iphone-xr')
        //actions
        cy.wait(1200)
        cy.get('.control').click()
        cy.wait(1000)
        cy.get('.nav-link').eq(1).click()
        cy.wait(5000)
        cy.get('.control').click()
        cy.wait(1500)
        cy.get('.nav-link').eq(3).click()
    })
  })
  